config_version = '3.1.0'
window_h_pos = 200
window_v_pos = 200
soundboard_hotkeys = []

[youtube_dl]
bin_path = 'C:/Users/igorm/CODE/yt-dlp.exe'
extra_arguments = []

[audio_config]
main_device_on = true
only_one_sound_at_once = false
volume_multiplier = 1.0
volume_multiplier_base = 1.25
additional_device_id = 'null'
audio_cache_location = '.audio_cache'
prefered_universal_format = 'mp3'

[tts_config]
language = 'en'
prompt = ''
[[app_hotkeys.toggle_main_device_playback.keys]]
name = '/'
vk = 111

[[app_hotkeys.toggle_main_device_playback.keys]]
name = '-'
vk = 109
[[app_hotkeys.toggle_singular_playback.keys]]
name = '/'
vk = 111

[[app_hotkeys.toggle_singular_playback.keys]]
name = '*'
vk = 106
[[app_hotkeys.increase_volume.keys]]
name = '+'
vk = 107

[[app_hotkeys.increase_volume.keys]]
name = '*'
vk = 106
[[app_hotkeys.decrease_volume.keys]]
name = '-'
vk = 109

[[app_hotkeys.decrease_volume.keys]]
name = '*'
vk = 106
[[app_hotkeys.stop_all_sounds.keys]]
name = 'End'
vk = 35
[[app_hotkeys.play_cached_tts.keys]]
name = '['
vk = 219
[[app_hotkeys.open_tts_manager.keys]]
name = ']'
vk = 221
[[app_hotkeys.next_page.keys]]
name = 'page_up'
vk = 33
[[app_hotkeys.previous_page.keys]]
name = 'page_down'
vk = 34
