DEFAULT_CUSTOM_FOLDER = "default_custom"
TEMP_TTS_FILE = "tempTTS.ogg"
TEMP_YTDL_FILE = "tempYTDL.mp3"
CONFIG_FILENAME = "config.json"
TEMP_TTS_FILE_MP3 = "tempTTS.mp3"
DEFAULT_SOUND_MULTIPLIER = 1.5
